# Generated by Django 4.2.4 on 2023-09-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=30)),
                ('interests', models.TextField(max_length=200)),
                ('pros', models.TextField(max_length=200)),
                ('cons', models.TextField(max_length=200)),
            ],
        ),
    ]
